export const SHARE_POST_REQUEST = "SHARE_POST_REQUEST";
export const SHARE_POST_SUCCESS = "SHARE_POST_SUCCESS";
export const SHARE_POST_FAILURE = "SHARE_POST_FAILURE";

export const GET_POST_SHARES_REQUEST = "GET_POST_SHARES_REQUEST";
export const GET_POST_SHARES_SUCCESS = "GET_POST_SHARES_SUCCESS";
export const GET_POST_SHARES_FAILURE = "GET_POST_SHARES_FAILURE";

export const DELETE_POST_SHARE_REQUEST = "DELETE_POST_SHARE_REQUEST";
export const DELETE_POST_SHARE_SUCCESS = "DELETE_POST_SHARE_SUCCESS";
export const DELETE_POST_SHARE_FAILURE = "DELETE_POST_SHARE_FAILURE";
