export const SEND_FRIEND_REQUEST_REQUEST = "SEND_FRIEND_REQUEST_REQUEST";
export const SEND_FRIEND_REQUEST_SUCCESS = "SEND_FRIEND_REQUEST_SUCCESS";
export const SEND_FRIEND_REQUEST_FAILURE = "SEND_FRIEND_REQUEST_FAILURE";

export const CANCEL_FRIEND_REQUEST_REQUEST = "CANCEL_FRIEND_REQUEST_REQUEST";
export const CANCEL_FRIEND_REQUEST_SUCCESS = "CANCEL_FRIEND_REQUEST_SUCCESS";
export const CANCEL_FRIEND_REQUEST_FAILURE = "CANCEL_FRIEND_REQUEST_FAILURE";

export const ACCEPT_FRIEND_REQUEST_REQUEST = "ACCEPT_FRIEND_REQUEST_REQUEST";
export const ACCEPT_FRIEND_REQUEST_SUCCESS = "ACCEPT_FRIEND_REQUEST_SUCCESS";
export const ACCEPT_FRIEND_REQUEST_FAILURE = "ACCEPT_FRIEND_REQUEST_FAILURE";

export const REFUSE_FRIEND_REQUEST_REQUEST = "REFUSE_FRIEND_REQUEST_REQUEST";
export const REFUSE_FRIEND_REQUEST_SUCCESS = "REFUSE_FRIEND_REQUEST_SUCCESS";
export const REFUSE_FRIEND_REQUEST_FAILURE = "REFUSE_FRIEND_REQUEST_FAILURE";

export const UNFRIEND_REQUEST = "UNFRIEND_REQUEST";
export const UNFRIEND_SUCCESS = "UNFRIEND_SUCCESS";
export const UNFRIEND_FAILURE = "UNFRIEND_FAILURE";

export const GET_FRIENDS_REQUEST = "GET_FRIENDS_REQUEST";
export const GET_FRIENDS_SUCCESS = "GET_FRIENDS_SUCCESS";
export const GET_FRIENDS_FAILURE = "GET_FRIENDS_FAILURE";

export const GET_FRIEND_REQUESTS_RECEIVED_REQUEST = "GET_FRIEND_REQUESTS_RECEIVED_REQUEST";
export const GET_FRIEND_REQUESTS_RECEIVED_SUCCESS = "GET_FRIEND_REQUESTS_RECEIVED_SUCCESS";
export const GET_FRIEND_REQUESTS_RECEIVED_FAILURE = "GET_FRIEND_REQUESTS_RECEIVED_FAILURE";

export const GET_FRIEND_STATUS_REQUEST = "GET_FRIEND_STATUS_REQUEST";
export const GET_FRIEND_STATUS_SUCCESS = "GET_FRIEND_STATUS_SUCCESS";
export const GET_FRIEND_STATUS_FAILURE = "GET_FRIEND_STATUS_FAILURE";
