export const JOIN_GROUP_REQUEST = "JOIN_GROUP_REQUEST";
export const JOIN_GROUP_SUCCESS = "JOIN_GROUP_SUCCESS";
export const JOIN_GROUP_FAILURE = "JOIN_GROUP_FAILURE";

export const LEAVE_GROUP_REQUEST = "LEAVE_GROUP_REQUEST";
export const LEAVE_GROUP_SUCCESS = "LEAVE_GROUP_SUCCESS";
export const LEAVE_GROUP_FAILURE = "LEAVE_GROUP_FAILURE";

export const GET_PENDING_MEMBERS_REQUEST = "GET_PENDING_MEMBERS_REQUEST";
export const GET_PENDING_MEMBERS_SUCCESS = "GET_PENDING_MEMBERS_SUCCESS";
export const GET_PENDING_MEMBERS_FAILURE = "GET_PENDING_MEMBERS_FAILURE";

export const APPROVE_MEMBER_REQUEST = "APPROVE_MEMBER_REQUEST";
export const APPROVE_MEMBER_SUCCESS = "APPROVE_MEMBER_SUCCESS";
export const APPROVE_MEMBER_FAILURE = "APPROVE_MEMBER_FAILURE";

export const REJECT_MEMBER_REQUEST = "REJECT_MEMBER_REQUEST";
export const REJECT_MEMBER_SUCCESS = "REJECT_MEMBER_SUCCESS";
export const REJECT_MEMBER_FAILURE = "REJECT_MEMBER_FAILURE";

export const DELETE_MEMBER_REQUEST = "DELETE_MEMBER_REQUEST";
export const DELETE_MEMBER_SUCCESS = "DELETE_MEMBER_SUCCESS";
export const DELETE_MEMBER_FAILURE = "DELETE_MEMBER_FAILURE";

export const GET_GROUP_MEMBERS_REQUEST = "GET_GROUP_MEMBERS_REQUEST";
export const GET_GROUP_MEMBERS_SUCCESS = "GET_GROUP_MEMBERS_SUCCESS";
export const GET_GROUP_MEMBERS_FAILURE = "GET_GROUP_MEMBERS_FAILURE";

export const GET_MEMBERSHIP_STATUS_REQUEST = "GET_MEMBERSHIP_STATUS_REQUEST";
export const GET_MEMBERSHIP_STATUS_SUCCESS = "GET_MEMBERSHIP_STATUS_SUCCESS";
export const GET_MEMBERSHIP_STATUS_FAILURE = "GET_MEMBERSHIP_STATUS_FAILURE";

export const CHECK_IS_ADMIN_REQUEST = "CHECK_IS_ADMIN_REQUEST";
export const CHECK_IS_ADMIN_SUCCESS = "CHECK_IS_ADMIN_SUCCESS";
export const CHECK_IS_ADMIN_FAILURE = "CHECK_IS_ADMIN_FAILURE";

export const UPDATE_MEMBER_ROLE_REQUEST = "UPDATE_MEMBER_ROLE_REQUEST";
export const UPDATE_MEMBER_ROLE_SUCCESS = "UPDATE_MEMBER_ROLE_SUCCESS";
export const UPDATE_MEMBER_ROLE_FAILURE = "UPDATE_MEMBER_ROLE_FAILURE";
