// Get notifications
export const GET_NOTIFICATIONS_REQUEST = "GET_NOTIFICATIONS_REQUEST";
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_FAILURE = "GET_NOTIFICATIONS_FAILURE";

// Get unread count
export const GET_UNREAD_COUNT_REQUEST = "GET_UNREAD_COUNT_REQUEST";
export const GET_UNREAD_COUNT_SUCCESS = "GET_UNREAD_COUNT_SUCCESS";
export const GET_UNREAD_COUNT_FAILURE = "GET_UNREAD_COUNT_FAILURE";

// Mark as read
export const MARK_AS_READ_REQUEST = "MARK_AS_READ_REQUEST";
export const MARK_AS_READ_SUCCESS = "MARK_AS_READ_SUCCESS";
export const MARK_AS_READ_FAILURE = "MARK_AS_READ_FAILURE";

// Mark all as read
export const MARK_ALL_AS_READ_REQUEST = "MARK_ALL_AS_READ_REQUEST";
export const MARK_ALL_AS_READ_SUCCESS = "MARK_ALL_AS_READ_SUCCESS";
export const MARK_ALL_AS_READ_FAILURE = "MARK_ALL_AS_READ_FAILURE";

// Delete notification
export const DELETE_NOTIFICATION_REQUEST = "DELETE_NOTIFICATION_REQUEST";
export const DELETE_NOTIFICATION_SUCCESS = "DELETE_NOTIFICATION_SUCCESS";
export const DELETE_NOTIFICATION_FAILURE = "DELETE_NOTIFICATION_FAILURE";

// WebSocket real-time
export const RECEIVE_NOTIFICATION = "RECEIVE_NOTIFICATION";

// Reset
export const RESET_NOTIFICATIONS = "RESET_NOTIFICATIONS";
