export const REACT_COMMENT_REQUEST = "REACT_COMMENT_REQUEST";
export const REACT_COMMENT_SUCCESS = "REACT_COMMENT_SUCCESS";
export const REACT_COMMENT_FAILURE = "REACT_COMMENT_FAILURE";

export const UNREACT_COMMENT_REQUEST = "UNREACT_COMMENT_REQUEST";
export const UNREACT_COMMENT_SUCCESS = "UNREACT_COMMENT_SUCCESS";
export const UNREACT_COMMENT_FAILURE = "UNREACT_COMMENT_FAILURE";

export const GET_COMMENT_REACTIONS_REQUEST = "GET_COMMENT_REACTIONS_REQUEST";
export const GET_COMMENT_REACTIONS_SUCCESS = "GET_COMMENT_REACTIONS_SUCCESS";
export const GET_COMMENT_REACTIONS_FAILURE = "GET_COMMENT_REACTIONS_FAILURE";

export const GET_MY_COMMENT_REACTION_REQUEST = "GET_MY_COMMENT_REACTION_REQUEST";
export const GET_MY_COMMENT_REACTION_SUCCESS = "GET_MY_COMMENT_REACTION_SUCCESS";
export const GET_MY_COMMENT_REACTION_FAILURE = "GET_MY_COMMENT_REACTION_FAILURE";
