export const CREATE_GROUP_REQUEST = "CREATE_GROUP_REQUEST";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAILURE = "CREATE_GROUP_FAILURE";

export const GET_GROUPS_REQUEST = "GET_GROUPS_REQUEST";
export const GET_GROUPS_SUCCESS = "GET_GROUPS_SUCCESS";
export const GET_GROUPS_FAILURE = "GET_GROUPS_FAILURE";

export const GET_GROUP_BY_ID_REQUEST = "GET_GROUP_BY_ID_REQUEST";
export const GET_GROUP_BY_ID_SUCCESS = "GET_GROUP_BY_ID_SUCCESS";
export const GET_GROUP_BY_ID_FAILURE = "GET_GROUP_BY_ID_FAILURE";

export const UPDATE_GROUP_REQUEST = "UPDATE_GROUP_REQUEST";
export const UPDATE_GROUP_SUCCESS = "UPDATE_GROUP_SUCCESS";
export const UPDATE_GROUP_FAILURE = "UPDATE_GROUP_FAILURE";

export const DELETE_GROUP_REQUEST = "DELETE_GROUP_REQUEST";
export const DELETE_GROUP_SUCCESS = "DELETE_GROUP_SUCCESS";
export const DELETE_GROUP_FAILURE = "DELETE_GROUP_FAILURE";

export const SEARCH_GROUPS_REQUEST = "SEARCH_GROUPS_REQUEST";
export const SEARCH_GROUPS_SUCCESS = "SEARCH_GROUPS_SUCCESS";
export const SEARCH_GROUPS_FAILURE = "SEARCH_GROUPS_FAILURE";

export const GET_MY_GROUPS_REQUEST = "GET_MY_GROUPS_REQUEST";
export const GET_MY_GROUPS_SUCCESS = "GET_MY_GROUPS_SUCCESS";
export const GET_MY_GROUPS_FAILURE = "GET_MY_GROUPS_FAILURE";

export const GET_GROUP_POSTS_REQUEST = "GET_GROUP_POSTS_REQUEST";
export const GET_GROUP_POSTS_SUCCESS = "GET_GROUP_POSTS_SUCCESS";
export const GET_GROUP_POSTS_FAILURE = "GET_GROUP_POSTS_FAILURE";

export const GET_GROUP_PENDING_POSTS_REQUEST = "GET_GROUP_PENDING_POSTS_REQUEST";
export const GET_GROUP_PENDING_POSTS_SUCCESS = "GET_GROUP_PENDING_POSTS_SUCCESS";
export const GET_GROUP_PENDING_POSTS_FAILURE = "GET_GROUP_PENDING_POSTS_FAILURE";

export const CREATE_GROUP_POST_REQUEST = "CREATE_GROUP_POST_REQUEST";
export const CREATE_GROUP_POST_SUCCESS = "CREATE_GROUP_POST_SUCCESS";
export const CREATE_GROUP_POST_FAILURE = "CREATE_GROUP_POST_FAILURE";

export const APPROVE_GROUP_POST_REQUEST = "APPROVE_GROUP_POST_REQUEST";
export const APPROVE_GROUP_POST_SUCCESS = "APPROVE_GROUP_POST_SUCCESS";
export const APPROVE_GROUP_POST_FAILURE = "APPROVE_GROUP_POST_FAILURE";
